on:
 push:
  branches: 'test'

jobs:
 run_tests:
   runs-on: [ubuntu-latest]
   steps:
     # Чекаутим код
     - uses: actions/checkout@v2
       # Устанавливаем python нужной версии
     - uses: actions/setup-python@v1
       with:
         python-version: '3.9'
         architecture: 'x64'
     - name: Install requirements
       # Устанавливаем зависимости
       run: pip install -r requirements.txt
     - name: Run tests
       run: coverage run tests.py
     - name: Tests report
       run: coverage report